# This is a basic workflow to help you get started with Actions

name: GenerateList

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: make list
        run:
          ls > a.txt
      - name: archive
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'a.txt'
          destination_repo: 'ro1y/gitroly'
          user_email: 'ro1y@protonmail.ch'
          user_name: 'ro1y'
          commit_message: 'Uploading 88x31 lizt'
