# This is a basic workflow to help you get started with Actions

name: GenerateList

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: make list
        run:
          ls > a.txt
      - name: archive
        uses: actions/upload-artifact@v3
        with:
          name: list-files
          path: a.txt
